baseurl = "https://sudocast.github.io/"
languageCode = "pt-BR"
title = "SudoCast"
theme = "castanet"
# googleAnalytics = "UA-100789009-1"
disqusShortname = "perylemke"
themesdir = "./themes"
paginate = "9"

[permalinks]
    page = "/:filename/"
    about = "/:filename/"
    episode = "/:filename/"

# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
[[Menu.Main]]
    name = "Contato"
    identifier = "2"
    url = "contact"

[[Menu.Main]]
    name = "Hosts"
    identifier = "0"
    url = "host"

[[Menu.Main]]
    name = "Convidados"
    identifier = "1"
    url = "guest"

[params]
site_theme = "grey"
# site_layout = "grid|row"
site_layout = "grid"
enable_jumbo = "true"
# enable_jumbo = "false"
# truncate = "100"
about_logo = "/img/logo.jpg"
copyright_notice = "Copyright 2018 [sudocast](http://www.sudocast.com.br)"
itunes_subscribe = "https://itunes.apple.com/br/podcast/sudocast/id1229109698?mt=2"
#android_subscribe = "http://subscribeonandroid.com/feeds.podtrac.com/VGAulpN7MY1U"
#google_play_subscribe = "https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ihj4yege3lfmp3vs5yoopgxijpi?t%3DArrested_DevOps"
#stitcher_subscribe = "http://www.stitcher.com/podcast/arrested-devops-2/arrested-devops"
#soundcloud_subscribe = "http://feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
#pocketcasts_subscribe = "http://pcasts.in/feed/feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
#mailchimp_subscribe = "//arresteddevops.us3.list-manage.com/subscribe/post?u=5e4cbcac996bb9df25f970a89&amp;id=154fa76bcc"
#rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
description = "Esse é o Sudocast, somos um podcast de tecnologia de humor ácido, engraçado que discute os principais temas em voga no mundo de Desenvolvimento de Software."
media_prefix = "http://media.blubrry.com/sudocast1/content.blubrry.com/sudocast1/"
custom_css = ["css/custom.css"]
  [params.feed]
    feed_copyright = "Copyright 2017 Pery Lemke and Mário Silveira" #do not use markdown in this field; it is used in the feed
    itunes_subtitle = "Um podcast de tecnologia e tendências!" #no markdown or HTML
    itunes_author = "Pery Lemke" #no markdown or HTML
    itunes_summary = "Sudocast vem a ser um podcast de tecnologia ácido, engraçado e dinâmico onde são discutidos os assuntos mais quentes do mundo de desenvolvimento." # Limited to 4000 characters or less, plain text, no HTML
    itunes_owner_name = "Pery Lemke"
    itunes_owner_email = "pery.lemke@gmail.com" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on iTunes. It will not be publicly displayed on iTunes.
    itunes_image = "https://www.arresteddevops.com/img/ado-podcast-logo.png" #fqdn to the image art for your podcast
    itunes_top_category = "Technology"
    itunes_first_sub_category = "Software How-To"
    itunes_second_sub_category = "Tech News"

  [params.social]
    github = "sudocast"
    facebook = "1sudocast"
    #facebook_admin = "500557137"  # This needs to be a page admin to get domain insights
    twitter = "sudocast"
    instagram = "sudocast"
    # youtube = "testafterdeploy"
    # linkedin = "/perylemke"

  [params.authors]
    [params.authors.Pery]
      name  = "Pery Lemke"
      thumbnail = "img/host/pery.png"
      bio = ""
      [params.authors.Pery.social]
        github = "perylemke"
        twitter = "perylemke"
        linkedin = "perylemke"
        homepage = ""
        instagram = "perylemke"
        youtube = "testafterdeploy"
    [params.authors.Mario]
      name = "Mário Silveira"
      thumbnail = "img/host/mario.png"
      bio = ""
      [params.authors.Mario.social]
        twitter = "dermarios"
    [params.authors.Leroy]
      name = "Igor Leroy"
      thumbnail = "img/host/leroy.png"
      bio = ""
      [params.authors.Leroy.social]
        twitter = "lerrua"
        github = "lerrua"
        linkedin = "igorleroy"

    [params.links]
      [params.links.ado]
        name = "Arrested DevOps"
        url = "https://www.arresteddevops.com"
      [params.links.ffs]
        name = "Food Fight Show"
        url = "https://foodfightshow.org"
      [params.links.sdt]
        name = "Software Defined Talk"
        url = "https://cote.io/podcasts/sdt/"
